calc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('operaciones.urls', 'operaciones'), namespace='operaciones')),
    path('admin/', admin.site.urls),
]

operaciones/urls.py
from django.urls import path
#from . import views
from operaciones.views import Home
from . import views

urlpatterns = [
    path('', Home.as_view(), name='home'),  
    path('resultado', views.calculation, name='resultado'),
    path('repositorio', views.red_github, name='repositorio')
]

operaciones/models.py
from django.db import models

# Create your models here.

operaciones/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
import re

# Create your views here.
class Home(generic.TemplateView):
    template_name='base/calculadora.html'

def calculation(request):
    result=0
    msj_no_error=True
    result_error = ''
    if request.method=="POST":
        valores=request.POST['values'] #string having whole ques
        values=valores.replace(',','.')
        values=values.replace('/', '÷')
        values=values.replace('*', 'x')
        print("STEP 1-",values)
        vals=re.findall(r"(\d+)",values) #extrect values
        print("STEP 2- ",re.findall(r"(\d+)",values))
        operators=['.','%','x','÷','+','-']
        opr=[]  
        for v in values:
            for o in operators:
                if v==o:
                    print("STEP 3(SIMBOLO DE OPERADOR)=>", o)
                    opr.append(o)
        print("STEP 4- array operador =>",opr)                      #extrect operators
        #print(re.findall(r"(\d+)",values))

        for o in opr:
            
            if o=='.':
                i=opr.index(o)
                print("STEP 5(POSICION DEL ARRAY OPERADOR) => ", i)
                res=vals[i]+"."+vals[i+1]
                vals.remove(vals[i+1])
                opr.remove(opr[i])
                vals[i]=res
                print("STEP 6 =>", vals)
                print("STEP 7 =>", opr)
                
            elif o=='%':
                i=opr.index(o)
                mod= 0
                dec_por = float(vals[i+1])
                valor_por=float(vals[i])
                mod= dec_por%valor_por
                #res=float(vals[i])+valor_por
                res= float(mod)
                vals.remove(vals[i+1])
                opr.remove(opr[i])
                vals[i]=res
                print(vals)
                print(opr)   
                
            elif o=='÷':
                i=opr.index(o)
                res=0
                try:
                    res=float(vals[i])/float(vals[i+1])
                except ZeroDivisionError:
                    msj_no_error=False
                    result_error = result_error + "ERROR_VALOR_INDEFINIDO"
                except Exception as e:
                    print(type(e))
                finally: 
                    vals.remove(vals[i+1])
                    opr.remove(opr[i])
                    vals[i]=str(res)
                    print(vals)
                    print(opr)
                    
            elif o=='x':
                i=opr.index(o)
                print("Step4- ", i)
                res=float(vals[i])*float(vals[i+1])
                vals.remove(vals[i+1])
                opr.remove(opr[i])
                vals[i]=str(res)
                print(vals)
                print(opr)
                
            elif o=='+':
                i=opr.index(o)
                res=float(vals[i])+float(vals[i+1])
                vals.remove(vals[i+1])
                opr.remove(opr[i])
                vals[i]=str(res)
                print(vals)
                print(opr)
                
            elif o=='-':
                i=opr.index(o)
                res=float(vals[i])-float(vals[i+1])
                vals.remove(vals[i+1])
                opr.remove(opr[i])
                vals[i]=str(res)
                print(vals)
                print(opr)

        # print(opr)
        if len(opr)!=0:
            if opr[0]=='÷':
                try:
                    result = float(vals[0])/float(vals[1])
                except ZeroDivisionError:
                    msj_no_error=False
                    result_error = result_error + "ERROR_VALOR_INDEFINIDO"
                except Exception as e:
                    print(type(e))
            elif opr[0]=='x':
                result = float(vals[0])*float(vals[1])
            elif opr[0]=='+':
                result = float(vals[0])+float(vals[1])
            #error  
            elif opr[0]=='%':
                mod=0
                conv_dec=float(vals[1])
                valor_porc=float(vals[0])
                #result = float(vals[0] + valor_porc)   
                result= float(mod) 
           # else :
               # result = float(vals[0])-float(vals[1])
                
        else:
            try:
                result = float(vals[0])
            except IndexError:
                msj_no_error=False
                result_error= result_error+"ERROR_INGRESE_VALOR_TIPO_NUMÉRICO"
                print(result_error)
            except Exception as e:
                print(type(e))
        
    if(msj_no_error):
        final_result=round(result,4)
        print("Resultado final =>", final_result)
        res=render(request,'base/calculadora.html',{'result':final_result,'values':values})
        return res
    else:
        res_error=render(request, 'base/calculadora.html', {'result': result_error, 'values': valores})
        print("retornamos valor erroneo")
        return res_error
    
def red_github(request):
    return HttpResponseRedirect("https://github.com/Ricardo-20/calculator_js_django")

templates/base/calculadora.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Calculadora</title>
    <link rel="stylesheet" href= "{% static 'base/css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Alata&family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
  </head>
  <body id="fondo">
    <section id="first">
      <div class="container-fluid">
      
        <div class="col-sm-12 header">
      
          <div class="row">
            <div class="col-md-6">
              <ion-icon name="calculator-outline"></ion-icon>
              Calculadora
            </div>
            <div class="col-md-6">
              <a href={% url 'operaciones:repositorio'%} target="_blank"><ion-icon name="logo-github"></ion-icon></a>
              <ion-icon name="logo-python"></ion-icon>
              <ion-icon name="logo-nodejs"></ion-icon>
              <ion-icon name="logo-html5"></ion-icon>
              <ion-icon name="logo-css3"></ion-icon>
            </div>
          </div>
          <!--
              <ion-icon name="calculator-outline"></ion-icon>
              Calculator
              -->
        </div>
      
      
      </div>
    </section>
    <section id="second">
      <form class="" action="resultado" method="post">
        {% csrf_token %}
      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-2 left">
            <!-- left -->
          </div>
          <div class="col-sm-8 middle">
            <!-- main -->
            <div class="result">
              <span id="ques">{{values}}</span>
              <input type="text" name="values" id= "result" placeholder="0" value={{result}} >
            </div>
            <div class="keypad">
              <div class="row">
                <div class="col-sm-1">

                </div>
                <div class="col-sm-2">
                  <button type="button" class="btn btn-block spc_btn" id="left_small" onclick="insertTextInInputValue('(');">(</button>
                </div>
                <div class="col-sm-2">
                  <button type="button" class="btn btn-block spc_btn" onclick="insertTextInInputValue(')');">)</button>
                </div>
                <div class="col-sm-2">
                  <button type="button" class="btn btn-block spc_btn" onclick="insertTextInInputValue('%');">%</button>
                </div>
                <div class="col-sm-2">
                  <button type="button" class="btn btn-block spc_btn" onclick="insertTextInInputValue('AC');">AC</button>
                </div>
                <div class="col-sm-2">
                  <button type="button" class="btn btn-block del_btn" onclick="borrarDel('←');">←</button>
                </div>
                <div class="col-sm-1">
                  
                </div>
              </div>
              <div class="row">
                <div class="col-sm-1">

                </div>
                <div class="col-sm-2">
                  <button type="button" class="btn btn-block num_btn" onclick="insertTextInInputValue(7);">7</button>
                </div>
                <div class="col-sm-2">
                  <button type="button" class="btn btn-block num_btn" onclick="insertTextInInputValue(8);">8</button>
                </div>
                <div class="col-sm-2">
                  <button type="button" class="btn btn-block num_btn" onclick="insertTextInInputValue(9);">9</button>
                </div>
                <div class="col-sm-2">
                   <button type="button" class="btn btn-block spc_btn" onclick="insertTextInInputValue('&divide');">&#247;</button>
                </div>
                <div class="col-sm-2">
                  <button type="submit" class="btn btn-block btn-primary equal_btn">=</button>
               </div>
                <div class="col-sm-1">

                </div>
              </div>
              <div class="row">
                <div class="col-sm-1">

                </div>
                <div class="col-sm-2">
                  <button type="button" class="btn btn-block num_btn" onclick="insertTextInInputValue(4);">4</button>
                </div>
                <div class="col-sm-2">
                  <button type="button" class="btn btn-block num_btn" onclick="insertTextInInputValue(5);">5</button>
                </div>
                <div class="col-sm-2">
                  <button type="button" class="btn btn-block num_btn" onclick="insertTextInInputValue(6);">6</button>
                </div>
                <div class="col-sm-2">
                  <button type="button" class="btn btn-block spc_btn" onclick="insertTextInInputValue('x');">&#215;</button>
                </div>
                <div class="col-sm-1">

                </div>
              </div>
              <div class="row">
                <div class="col-sm-1">

                </div>
                <div class="col-sm-2">
                  <button type="button" class="btn btn-block num_btn" onclick="insertTextInInputValue(1);">1</button>
                </div>
                <div class="col-sm-2">
                  <button type="button" class="btn btn-block num_btn" onclick="insertTextInInputValue(2);">2</button>
                </div>
                <div class="col-sm-2">
                  <button type="button" class="btn btn-block num_btn" onclick="insertTextInInputValue(3);">3</button>
                </div>
                <div class="col-sm-2">
                  <button type="button" class="btn btn-block spc_btn" onclick="insertTextInInputValue('-');">-</button>
                </div>
                <div class="col-sm-1">

                </div>
              </div>
              <div class="row">
                <div class="col-sm-1">

                </div>
                <div class="col-sm-2">
                  <button type="button" class="btn btn-block num_btn" onclick="insertTextInInputValue(0);">0</button>
                </div>
                <div class="col-sm-2">
                  <button type="button" class="btn btn-block spc_btn" onclick="insertTextInInputValue('.');">.</button>
                </div>
                <!--<div class="col-sm-2">
                  <button type="submit" class="btn btn-block btn-primary equal_btn">=</button>
                </div>-->
                <!--<div class="col-sm-2">
                  <button type="button" class="btn btn-block spc_btn" onclick="insertTextInInputValue('+');">+</button>
                </div>-->
                <div class="col-sm-3">
                  <button type="button" class="btn btn-block plu_btn" onclick="insertTextInInputValue('+');">+</button>
                </div>
                <div class="col-sm-1">

                </div>
              </div>
            </div>
          </div>
          <div class="col-sm-2 right">
            <!-- right -->
          </div>
        </div>
      </div>
      </form>
    </section>
    <footer>
      <div id="pieDePagina" class="container">
        <ul class="nav">
          <li><a href="#">Integrantes: </a></li>
          <li> <a href="#">-Juarez Quispe, Ricardo</a></li>
          <li><a href="#">-Espinoza Rojas, Ebert</a></li>
          <li><a href="#">-Flores Chalco, Jamil</a></li>
          <li><a href="#">-Roldan Goñaz, Roldan</a></li>
        </ul>
      </div>
    </footer>
    <script src= "{%static 'base/js/main.js' %}"></script>
  </body>
  <script src="https://unpkg.com/ionicons@5.1.2/dist/ionicons.js"></script>
  <script type="text/javascript">
  //function insertTextInInputValue(buttonValueIs){
  //          if (buttonValueIs == "AC")
  //          {
  //            $('#ques').text('Ans : 0');
  //            $('#result').val(0);
  //          }
  //          else {
  //            var inputElementIs = document.getElementById("result");
  //            inputElementIs.value =  inputElementIs.value + buttonValueIs;
  //            $('#result').val(inputElementIs.value);
  //          }
  //      }
// $('#tussenstand').val("Total: "+theTotal);
  </script>
  
</html>